Repository TheBestTvarynka/crypto-helper, pull requests merged in 2023-04, with the labels that each got.

#1 JWT
  .gitignore
  Cargo.lock
  Cargo.toml
  index.html
  public/styles/input.scss
  public/styles/jwt.scss
  public/styles/style.scss
  src/about.rs
  src/common/bytes_viewer.rs
  src/common/mod.rs
  src/common/simple_input.rs
  src/common/simple_output.rs
  src/crypto_helper/algorithm.rs
  src/crypto_helper/input.rs
  src/crypto_helper/input/krb.rs
  src/crypto_helper/output.rs
  src/crypto_helper/output/simple.rs
  src/jwt.rs
  src/jwt/jwt.rs
  src/jwt/jwt/editor.rs
  src/jwt/jwt/viewer.rs
  src/jwt/jwt_utils.rs
  src/jwt/jwte.rs
  src/jwt/macros.rs
  src/jwt/signature.rs
  src/main.rs
  src/utils.rs
Labels: enhancement

#15 Run CI checks on pull request
  .github/workflows/check-pr.yml
  src/jwt/jwt_utils.rs
  src/jwt/macros.rs
Labels: CI

#10 ByteInput component
  Cargo.lock
  Cargo.toml
  public/styles/input.scss
  src/common/byte_input.rs
  src/common/mod.rs
  src/common/simple_input.rs
  src/common/simple_output.rs
  src/crypto_helper.rs
  src/crypto_helper/algorithm.rs
  src/crypto_helper/input.rs
  src/jwt.rs
  src/jwt/jwt/editor.rs
  src/jwt/jwt_utils.rs
  src/jwt/macros.rs
  src/jwt/signature.rs
Labels: enhancement

#14 feat(crypto helper):jwt_implement_ES384_signature_algorithm
  Cargo.toml
  README.md
  src/about.rs
  src/jwt/jwt_utils.rs
  src/jwt/macros.rs
  src/jwt/signature.rs
Labels: enhancement, jwt

#17 feat(crypto helper):jwt_implement_ES512_signature_algorithm
  README.md
  src/about.rs
  src/jwt/jwt_utils.rs
  src/jwt/signature.rs
Labels: crypto-helper

#19 feat(crypto helper):crypto_halper_implement_SHA384
  README.md
  src/about.rs
  src/crypto_helper.rs
  src/crypto_helper/algorithm.rs
  src/crypto_helper/info.rs
  src/crypto_helper/input.rs
  src/crypto_helper/output.rs
Labels: crypto-helper

#20 Feat(crypto helper) fancy algo list
  src/crypto_helper.rs
  src/crypto_helper/algorithm.rs
  src/crypto_helper/info.rs
  src/crypto_helper/macros.rs
Labels: enhancement

#21 crypto-helper: Add Decimal and Binary byte formats
  src/common/mod.rs
  src/utils.rs
Labels: enhancement
